        /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;
import br.ulbra.view.MainView;
import br.ulbra.dao.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno.saolucas
 */
public class ChamadoView extends javax.swing.JFrame {

    /**
     * Creates new form ChamadoView
     */
    public ChamadoView() {
        
    initComponents();
    setLocationRelativeTo(null);
    carregarTabela();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SalvarBtn = new javax.swing.JButton();
        ListarBtn = new javax.swing.JButton();
        EditarBtn = new javax.swing.JButton();
        ExcluirBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSolicitante = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPatrimonio = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLocal = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtProblema = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtData = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextPane();
        cbPrioridade = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SalvarBtn.setText("Salvar");
        SalvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBtnActionPerformed(evt);
            }
        });

        ListarBtn.setText("Listar");
        ListarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarBtnActionPerformed(evt);
            }
        });

        EditarBtn.setText("Editar");
        EditarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBtnActionPerformed(evt);
            }
        });

        ExcluirBtn.setText("Excluir");
        ExcluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBtnActionPerformed(evt);
            }
        });

        txtSolicitante.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.selectionBackground"));
        txtSolicitante.setBorder(javax.swing.BorderFactory.createTitledBorder("Solicitante:"));
        jScrollPane1.setViewportView(txtSolicitante);

        txtPatrimonio.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.selectionBackground"));
        txtPatrimonio.setBorder(javax.swing.BorderFactory.createTitledBorder("Patrimônio/Tag:"));
        jScrollPane4.setViewportView(txtPatrimonio);

        txtLocal.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.selectionBackground"));
        txtLocal.setBorder(javax.swing.BorderFactory.createTitledBorder("Local/Sala:"));
        jScrollPane2.setViewportView(txtLocal);

        txtProblema.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.selectionBackground"));
        txtProblema.setBorder(javax.swing.BorderFactory.createTitledBorder("Problema Relatado:"));
        jScrollPane5.setViewportView(txtProblema);

        txtData.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.selectionBackground"));
        txtData.setBorder(javax.swing.BorderFactory.createTitledBorder("Data:"));
        jScrollPane6.setViewportView(txtData);

        txtDiagnostico.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.selectionBackground"));
        txtDiagnostico.setBorder(javax.swing.BorderFactory.createTitledBorder("Diagnóstico Técnico:"));
        jScrollPane7.setViewportView(txtDiagnostico);

        cbPrioridade.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        cbPrioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixa", "Média", "Alta" }));
        cbPrioridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPrioridadeActionPerformed(evt);
            }
        });

        jLabel2.setText("Prioridade:");

        Tabela.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Solicitante", "Patrimônio", "Local", "Prioridade", "Problema", "Diagnóstico", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tabela);

        jLabel3.setText("Status:");

        cbStatus.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Concluído", "Em andamento" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        btnVoltar.setText("Retornar p/ Menu");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(SalvarBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ListarBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditarBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExcluirBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVoltar)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarBtn)
                    .addComponent(ListarBtn)
                    .addComponent(EditarBtn)
                    .addComponent(ExcluirBtn)
                    .addComponent(btnVoltar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void carregarTabela() {
    DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
    modelo.setRowCount(0);

    String sql = "SELECT * FROM chamado_tecnico ORDER BY id";

    try (Connection con = ConnectionFactory.getConnection();
         PreparedStatement pst = con.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("solicitante"),
                rs.getString("patrimonio"),
                rs.getString("local_sala"),
                rs.getString("prioridade"),
                rs.getString("problema"),
                rs.getString("diagnostico"),
                rs.getString("status")
            });
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());
    }
}
    private void SalvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBtnActionPerformed
    try {
        String sql = "INSERT INTO chamado_tecnico "
                + "(solicitante, patrimonio, local_sala, data_chamado, prioridade, problema, diagnostico, status) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        Connection con = ConnectionFactory.getConnection();
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, txtSolicitante.getText().trim());
        pst.setString(2, txtPatrimonio.getText().trim());
        pst.setString(3, txtLocal.getText().trim());
        pst.setString(4, txtData.getText().trim());
        pst.setString(5, cbPrioridade.getSelectedItem().toString());
        pst.setString(6, txtProblema.getText().trim());
        pst.setString(7, txtDiagnostico.getText().trim());
        pst.setString(8, cbStatus.getSelectedItem().toString());

        pst.executeUpdate();

JOptionPane.showMessageDialog(this, "Chamado salvo com sucesso!");

        carregarTabela();

        pst.close();
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar chamado: " + e.getMessage());
    }
    }//GEN-LAST:event_SalvarBtnActionPerformed

    private void EditarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBtnActionPerformed
    int linha = Tabela.getSelectedRow();

    if (linha == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um chamado na tabela para editar!");
        return;
    }

    try {
        int id = Integer.parseInt(Tabela.getValueAt(linha, 0).toString());

        String sql = "UPDATE chamado_tecnico SET "
                + "solicitante = ?, "
                + "patrimonio = ?, "
                + "local_sala = ?, "
                + "data_chamado = ?, "
                + "prioridade = ?, "
                + "problema = ?, "
                + "diagnostico = ?, "
                + "status = ? "
                + "WHERE id = ?";

        Connection con = ConnectionFactory.getConnection();
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, txtSolicitante.getText().trim());
        pst.setString(2, txtPatrimonio.getText().trim());
        pst.setString(3, txtLocal.getText().trim());
        pst.setString(4, txtData.getText().trim());
        pst.setString(5, cbPrioridade.getSelectedItem().toString());
        pst.setString(6, txtProblema.getText().trim());
        pst.setString(7, txtDiagnostico.getText().trim());
        pst.setString(8, cbStatus.getSelectedItem().toString());
        pst.setInt(9, id);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Chamado editado com sucesso!");

        carregarTabela();

        pst.close();
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao editar chamado: " + e.getMessage());
    }
    }//GEN-LAST:event_EditarBtnActionPerformed

    private void cbPrioridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPrioridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPrioridadeActionPerformed

    private void ExcluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBtnActionPerformed
    int linha = Tabela.getSelectedRow();

    if (linha == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um chamado na tabela para excluir!");
        return;
    }

    int resposta = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente excluir este chamado?",
            "Confirmação",
            JOptionPane.YES_NO_OPTION
    );

    if (resposta == JOptionPane.YES_OPTION) {
        try {
            int id = Integer.parseInt(Tabela.getValueAt(linha, 0).toString());

            String sql = "DELETE FROM chamado_tecnico WHERE id = ?";

            Connection con = ConnectionFactory.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setInt(1, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Chamado excluído com sucesso!");

            carregarTabela();

            pst.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir chamado: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_ExcluirBtnActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
    new MainView().setVisible(true);
    dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void ListarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarBtnActionPerformed
    carregarTabela();
    }//GEN-LAST:event_ListarBtnActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
    int linha = Tabela.getSelectedRow();

    if (linha >= 0) {
        txtSolicitante.setText(Tabela.getValueAt(linha, 1).toString());
        txtPatrimonio.setText(Tabela.getValueAt(linha, 2).toString());
        txtLocal.setText(Tabela.getValueAt(linha, 3).toString());
        cbPrioridade.setSelectedItem(Tabela.getValueAt(linha, 4).toString());
        txtProblema.setText(Tabela.getValueAt(linha, 5).toString());
        txtDiagnostico.setText(Tabela.getValueAt(linha, 6).toString());
        cbStatus.setSelectedItem(Tabela.getValueAt(linha, 7).toString());
    }
    }//GEN-LAST:event_TabelaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChamadoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarBtn;
    private javax.swing.JButton ExcluirBtn;
    private javax.swing.JButton ListarBtn;
    private javax.swing.JButton SalvarBtn;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbPrioridade;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane txtData;
    private javax.swing.JTextPane txtDiagnostico;
    private javax.swing.JTextPane txtLocal;
    private javax.swing.JTextPane txtPatrimonio;
    private javax.swing.JTextPane txtProblema;
    private javax.swing.JTextPane txtSolicitante;
    // End of variables declaration//GEN-END:variables
}
